@url = http://localhost:8080/api/campaign/user
@token = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ0YWJsZXRvcCIsInN1YiI6ImRhbGUiLCJhdXRob3JpdGllcyI6IlJPTEVfVVNFUiIsImV4cCI6MTY1MzU3OTkwNn0.XoS3xOw1oWu7wzP_1R1uCJW_bg-qnG11edL7wSFp0tQ

###

POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "campaignid": 1,
    "user": {
        "userid": 1,
        "username": "a",
        "city": "a",
        "state": "a"
    }
}

###

DELETE {{url}}/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}