@url = http://localhost:8080/api/campaign/user
@token = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ0YWJsZXRvcCIsInN1YiI6ImRhbGUiLCJhdXRob3JpdGllcyI6IlJPTEVfVVNFUiIsInVzZXJJZCI6Miwic3RhdGUiOiJjYWxpZm9ybmlhIiwiY2l0eSI6IlNhY3JhbWVudG8iLCJleHAiOjE2NTM4ODQ3NTh9.PHBcZz7h5MjcbScv9y8C9jwDXoNXaB8v_ipqOGYUpbs

###

POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "campaignId": 2,
    "user": {
        "userId": 1,
        "username": "a",
        "city": "a",
        "state": "a"
    }
}

###

DELETE {{url}}/1/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}