@token = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ0YWJsZXRvcCIsInN1YiI6ImRhbGUiLCJhdXRob3JpdGllcyI6IiIsImV4cCI6MTY1MzUwOTk3N30.olibnOZrLAlNezkk3loX38Kvx70tM9YOYXhoqx8kTto

POST http://localhost:8080/api/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "dale",
    "password": "P@ssw0rd!"
}