@url = http://localhost:8080/api/session
@token = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ0YWJsZXRvcCIsInN1YiI6ImRhbGUiLCJhdXRob3JpdGllcyI6IlJPTEVfVVNFUiIsImV4cCI6MTY1MzU3ODQzMH0.bgWO_Ia2GjbL5I1gT70dDc80MQAgdXTzt_xVQ0b4sAc

###

GET {{url}}/use/2 HTTP/1.1

###

GET {{url}}/camp/2 HTTP/1.1

###

PUT {{url}}/4 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "sessionId": 4,
    "startDate": "2033-05-05T18:23:22.000+00:00",
    "endDate": "2033-05-06T23:59:17.000+00:00",
    "campaignId": 2
}

###

POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "startDate": "2033-05-10T19:23:22.000+00:00",
    "endDate": "2033-05-11T23:59:17.000+00:00",
    "campaignId": 2
}

###

DELETE {{url}}/10 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}