@url = http://localhost:8080/api/session/user
@token = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ0YWJsZXRvcCIsInN1YiI6ImRhbGUiLCJhdXRob3JpdGllcyI6IlJPTEVfVVNFUiIsImV4cCI6MTY1MzU4MjIwN30.FC1yMOkBrLngOb5dWp1WTzWeInMcbs1RnR7HKyum6WM

###

POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "sessionid": 2,
    "user": {
        "userid": 1,
        "username": "a",
        "city": "a",
        "state": "a"
    }
}

###

DELETE {{url}}/1/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}