@url = http://localhost:8080/api/userSchedule
@token = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ0YWJsZXRvcCIsInN1YiI6ImRhbGUiLCJhdXRob3JpdGllcyI6IlJPTEVfVVNFUiIsImV4cCI6MTY1MzU3OTcyNn0.HWgP_ES0zRGhjGgm0pJRAoCdWtcfGM4PE-x5sjq77DU

###

GET {{url}}/2 HTTP/1.1

###

PUT {{url}}/4 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "userScheduleid": 4,
    "startDate": "2033-05-05T20:23:22.000+00:00",
    "endDate": "2033-05-06T23:59:17.000+00:00",
    "userid": 1
}

###

POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "startDate": "2033-05-10T19:23:22.000+00:00",
    "endDate": "2033-05-11T23:59:17.000+00:00",
    "userid": 1
}

###

DELETE {{url}}/10 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}